# Generated by Django 5.2.1 on 2025-05-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机器人名称')),
                ('english_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='英文名称')),
                ('webhook_url', models.URLField(max_length=500, verbose_name='Webhook地址')),
                ('robot_type', models.CharField(choices=[('wechat', '企业微信'), ('feishu', '飞书'), ('dingtalk', '钉钉')], max_length=20, verbose_name='机器人类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '机器人配置',
                'verbose_name_plural': '机器人配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('robot_type', models.CharField(choices=[('wechat', '企业微信'), ('feishu', '飞书'), ('dingtalk', '钉钉')], max_length=20, verbose_name='适用机器人类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='发送内容')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='原始数据')),
                ('formatted_content', models.TextField(blank=True, null=True, verbose_name='格式化后内容')),
                ('status', models.BooleanField(default=False, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='push.robot', verbose_name='发送机器人')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='push.template', verbose_name='使用模板')),
            ],
            options={
                'verbose_name': '消息日志',
                'verbose_name_plural': '消息日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
