# Generated by Django 5.2.1 on 2025-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否为默认机器人'),
        ),
    ]
