# Generated by Django 5.2.1 on 2025-05-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_robot_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('type', models.CharField(choices=[('json', 'JSON模式'), ('string', '字符串模式')], max_length=20, verbose_name='匹配类型')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('extract_path', models.CharField(blank=True, max_length=500, verbose_name='JSON提取路径')),
                ('extract_pattern', models.CharField(blank=True, max_length=500, verbose_name='字符串提取模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分发规则',
                'verbose_name_plural': '分发规则',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255, unique=True, verbose_name='实例名称')),
                ('alert_count', models.IntegerField(default=0, verbose_name='告警次数')),
                ('last_alert_time', models.DateTimeField(blank=True, null=True, verbose_name='最后告警时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_mappings', to='push.robot', verbose_name='配置机器人')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_mappings', to='push.distributionrule', verbose_name='来源规则')),
            ],
            options={
                'verbose_name': '实例映射',
                'verbose_name_plural': '实例映射',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('alert_content', models.TextField(verbose_name='告警内容')),
                ('raw_data', models.TextField(verbose_name='原始数据')),
                ('extracted_values', models.JSONField(default=list, verbose_name='提取的值')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('instance_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_records', to='push.instancemapping', verbose_name='关联实例')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'ordering': ['-alert_time'],
            },
        ),
    ]
