# Generated by Django 5.2.1 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_distributionrule_instancemapping_alertrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancemapping',
            name='robot',
        ),
        migrations.AddField(
            model_name='instancemapping',
            name='robots',
            field=models.ManyToManyField(blank=True, related_name='instance_mappings', to='push.robot', verbose_name='配置机器人'),
        ),
    ]
