# Generated by Django 5.2.1 on 2025-05-29 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_remove_instancemapping_robot_instancemapping_robots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancemapping',
            name='robots',
        ),
        migrations.AlterField(
            model_name='instancemapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='DistributionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='通道名称')),
                ('description', models.TextField(blank=True, verbose_name='通道描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_channels', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_channels', to='push.robot', verbose_name='绑定机器人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_channels', to='push.template', verbose_name='绑定模板')),
            ],
            options={
                'verbose_name': '分发通道',
                'verbose_name_plural': '分发通道',
                'ordering': ['-updated_at'],
                'unique_together': {('robot', 'template')},
            },
        ),
        migrations.AddField(
            model_name='instancemapping',
            name='distribution_channels',
            field=models.ManyToManyField(blank=True, related_name='instance_mappings', to='push.distributionchannel', verbose_name='配置分发通道'),
        ),
    ]
